Filter name for creation time is called "started" instead of "created" #342
replicate/replicate pull request #489
Opened 2021-01-12 18:03 UTC by murthy95

Addresses #342

2021-01-12 18:15 UTC, andreasjansson requested changes
This looks good, thank you! Could we also change the default sort in `addListSortFlag` in cli/list.go? And then run `make docs` from the go/ folder to update the documentation?

2021-01-12 18:15 UTC, andreasjansson commented on go/pkg/param/filter.go
> +			console.Warn("Deprecated started use created instead")
```suggestion
			console.Warn("The filter name 'started' is deprecated, please use 'created' instead")
```

2021-01-12 18:15 UTC, andreasjansson commented on go/pkg/param/filter.go
>  	// "started" should probably be renamed/aliased to "created", see https://github.com/replicate/replicate/issues/342
we can remove this line now

2021-01-12 18:41 UTC, bfirsh commented
Thanks so much for the contribution @murthy95! You're also missing a sign-off on your commit, that certifies you're allowed to contribute to the project. If you click "Details" next to the failed DCO check, it has instructions on how to fix.

2021-01-13 15:55 UTC, andreasjansson approved these changes
Great, thanks again @murthy95 !

2021-01-13 15:56 UTC, merged